//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatZD.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EatZD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 function hello1(valid,code2,uid2,value){
        ///value = mask(valid + code2 + mask(&quot;voodoo_people_&quot; + uid2 + mask(value)));
        ///return value;
        ///} 的本地化字符串。
        /// </summary>
        internal static string strHello {
            get {
                return ResourceManager.GetString("strHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function mask(msg) {
        ///    
        ///    function rotate_left(n, s) {
        ///        var t4 = (n &lt;&lt; s) | (n &gt;&gt;&gt; (32 - s));
        ///        return t4;
        ///    }
        ///    ;
        ///    
        ///    function lsb_hex(val) {
        ///        var str = &quot;&quot;;
        ///        var i;
        ///        var vh;
        ///        var vl;
        ///        
        ///        for (i = 0; i &lt;= 6; i += 2) {
        ///            vh = (val &gt;&gt;&gt; (i * 4 + 4)) &amp; 0x0f;
        ///            vl = (val &gt;&gt;&gt; (i * 4)) &amp; 0x0f;
        ///            str += vh.toString(16) + vl.toString(16);
        ///        }
        ///        return str;
        ///    }
        ///    ;
        ///    
        ///    function  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string strMask {
            get {
                return ResourceManager.GetString("strMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function pin(r1,r2,u,code){
        ///var value = mask(r1 + r2 + mask(&quot;pin_&quot; + u + code));
        ///return value;
        ///} 的本地化字符串。
        /// </summary>
        internal static string strPin {
            get {
                return ResourceManager.GetString("strPin", resourceCulture);
            }
        }
    }
}
